### ISSUE TITLE
link to closed pullrequest

### ISSUE THREAD

**Issue by dni** [lnbits/jitsi#1]
just to not loose the context i link the old PR here.
https://github.com/lnbits/lnbits/pull/461

**Comment by nochiel** [comment]
@maxhillebrand [wrote](https://github.com/lnbits/lnbits/issues/211#issuecomment-1519114463):

> @nochiel @dni I'm so happy that this finally is happening! Thanks a bunch for implementing it, you guys rock.

> I think now is a good time to payout the 4 mil bounty, please reach out to me to coordinate in DM. npub1klkk3vrzme455yh9rl2jshq7rc8dpegj3ndf82c3ks2sk40dxt7qulx3vt

I still have a bit of work I want to do with the forked Jitsi client for a much better UX.

I also need to do more testing and improve robustness of the chatbot.

I'll ping you as I complete those milestones.

**Comment by ghost** [comment]
The best way to respond to a bounty payout suggestion is "No, I don't have time to take your sats, there's too much work to do!" lol 🖤

In any case, I'm ready and willing to pay out, so just ping me when you think it's ready. I'm happy to jump on a call to give some feedback as well.

**Comment by nochiel** [comment]
We're making progress @MaxHillebrand and @arcbtc. I dare say we're almost there:

![image](https://github.com/lnbits/jitsi/assets/284914/97759e87-e7a8-4d58-a2d0-e8f4a81e2ff4)

The UX will be fine-tuned but the functionality is almost all there:

![image](https://github.com/lnbits/jitsi/assets/284914/3252d40f-9195-48f4-ac75-0e42c26e8aa4)

**Comment by nochiel** [comment]
Hi @MaxHillebrand,

I wanted to give you an update of the work that's going on as well as the most recent updates, and to thank you for the generous bounty.

You can use the following addresses to send me sats: 

bc1qluptrwfg6xy0eugr8gt090kcyk2qac8rfh2etn

---

I've just submitted a PR (https://github.com/lnbits/jitsi/pull/2) to this repo to fix things that broke when changes to Jitsi and LNBits were made recently. @dni will give me access to push to the extension's repo soon. In the meantime, if you'd like to test, you can add this to the repo section of a manifest you use in an LNBits test instance:

```json
{
    "id": "jitsi",
    "organisation": "nochiel",
    "repository": "lnbits-jitsi-extension"
}
```

This only contains the chatbot functionality for interacting with LNBits.


---


The current roadmap for a full wallet UX is as follows:

- The screenshots I posted (https://github.com/lnbits/jitsi/issues/1#issuecomment-1656982366) are for prototype wallet functionality that I'm trying to get included in Jitsi. 

- The wallet functionality will allow us to have a nice UX for LNBits (or other Lightning Wallets) within Jitsi.

- I'm optimistic that this will be done by the end of summer *but* a lot of the work is in getting the PR into a condition that Jitsi will accept it into their codebase. As you can imagine, that's a significant amount of work involving a lot of back and forth, code reviews and so on. 

Right now I have my own version of Jitsi that I test with. In order to use this version that integrates with LNBits, it would also be necessary for you (or whomever wants to test it) to deploy their own Jitsi backend servers. 

(This would be the way to use a version of Jitsi with wallet functionality if it turns out that Jitsi don't want to include a wallet in their main product functionality on principle.)

**Comment by ghost** [comment]
Fantastic, thank you very much! The bounty is paid.

**Comment by nochiel** [comment]
> Fantastic, thank you very much! The bounty is paid.

🙇🏾‍♂️ Thank you, @MaxHillebrand. Do DM me on `npub1f3plgr8hr7xqf22jwzgrvdghahqlp98jklzwrjrmvrzpnfvq25js4xzznz` so I can keep you updated on the Jitsi PR (I'm not sure if the DMs I've sent you actually reached your relay 😨).

Have an awesome weekend. And, when the Jitsi PR is in review, I might need you to jump in the comments section to help me promote it a bit and convince them that it's worth having.

**Comment by ThomasFarstrike** [comment]
Just found about about this extension, this is great!

@nochiel Any link to the Jitsi PR? I can't find it at https://github.com/lnbits/jitsi/pulls

@nochiel Are the patches to Jitsi that should (ideally) be upstreamed available somewhere?
If not, would you please be able to publish them somewhere?
That would be another step towards the Jitsi PR. Thank you!

**Comment by nochiel** [comment]
Sorry I took so long to reply to this. Difficulties with my health delayed my progress and meant I had to prioritise other projects. 

> Just found about about this extension, this is great!
> 
> @nochiel Any link to the Jitsi PR? I can't find it at https://github.com/lnbits/jitsi/pulls

I'm going to clean up and complete what I have then get a pull request ready over the next 2 weeks. I'll post a link here to ping you as soon as it's up. 

> 
> @nochiel Are the patches to Jitsi that should (ideally) be upstreamed available somewhere? If not, would you please be able to publish them somewhere? That would be another step towards the Jitsi PR. Thank you!

I'll have an patched Docker image available for testing when the PR is ready.

Thanks again for your interest and encouragement. 🤗
